### PR TITLE
Revise UnitButtons logic and themes

### PR DESCRIPTION
**Pull request by Praytic**

### CODE REVIEW

**Review by Kvel2D — CHANGES_REQUESTED** [review]
Found an issue where cooldown indicator is drawn incorrectly:
2023-07-27 17_14_36-YouTD 2 (DEBUG)
Cooldown indicator should be drawn on top of button icon.

**Comment by Kvel2D** [comment]
Cooldown indicator is now rendering correctly.

Is the PR ready for review or is are you still working on it?

**Comment by Praytic** [comment]
> Is the PR ready for review or is are you still working on it?
It is ready for review

**Review by Kvel2D — APPROVED** [review]

**Comment by Kvel2D** [comment]
2023-07-29 20_57_40-YouTD 2 (DEBUG)
Found a bug. Extra space appears in ItemBar every time you move an item from ItemBar. Up to you if you want to fix before or after merging.

**Comment by Praytic** [comment]
> Found a bug. Extra space appears in ItemBar every time you move an item from ItemBar. Up to you if you want to fix before or after merging.

I will fix in my next PR

**Pull request merged**
