### PR TITLE
Implementations of suggested items QoL

### PR DESCRIPTION
**Pull request by PiotrKaszuba**
Referring #459 and #460.

Initially:
-  part of #459: item cooldowns visible in horadric cube but not yet in item stash.
- item charges also visible in horadric cube as an extension of #459
- point 5. of #460: horadric lock visible in tower and horadric lock state changeable in tower and horadric cube

### CODE REVIEW

**Comment by PiotrKaszuba** [comment]
- fully implemented point 3. of https://github.com/Praytic/youtd2/issues/460 with extensions: used ctrl click, generalized the idea - full description in commit implementing this: https://github.com/Praytic/youtd2/pull/462/commits/1419b7a951a6532dd49ed5ec76b51639b1b4bf2e

**Comment by PiotrKaszuba** [comment]
- implemented part of point 4. of #460: label showing average level of permanent items in horadric cube (turns out consumables/oils are level 0 and should be skipped for average level calculation for all recipes)

**Comment by PiotrKaszuba** [comment]
- implemented point 2. of #460 fully; also sorting by item type (permanent vs non-permanent) and item_id

**Comment by PiotrKaszuba** [comment]
- implemented point 6. of #460 fully

**Comment by PiotrKaszuba** [comment]
Rebased onto main that changed history of the branch.

**Comment by Kvel2D** [comment]
Hi, could you try to finalize this PR without point 1 from #460 ?
This PR is already quite big and point 1 is even more complex. Would be easier to review/merge if PR is not too big.

**Comment by PiotrKaszuba** [comment]
Hi, thank you for looking into this. I also think that point 1 from #460 should be left out.

I'll try to summarize state of changes vs #459 and #460. Then I'll point out additional thoughts about the PR.

This PR will:

#459 
- Show item cooldowns and charges in Horadric Cube. Missing either of these for item stash.

My thoughts on use cases: 
- (cooldowns) It allows the player to swap out of active items on towers and keep track of when to equip active items again to maximize their outputs - while keeping them in the Horadric Cube. My personal experience with keeping items there is "items that I'd often swap out" - between batches of cubing with recipes.
- (charges) My current use case was to gather (via recipe item grab button) many copies of "Strange item" and equip to towers those with low innate charges (higher future yield) and combine in the cube those with higher charges. I was able to spot better copies without equipping all copies separately. 

#460, point 1:
- Not implemented.

#460, point 2:
- Add additional button in upper right corner of item stash that reads "SORT". When clicked items in item stash will be sorted by: item type (consumables & oils then permanent items), then by item rarity, then by item level and then by item ID. While sorting stash blank spaces are removed.

My thoughts on use cases: 
- useful tool to tidy the item stash and help player find what they are looking for, helps planning item conversions with appropriate levels. When playtesting: I hit it often after a few items drop - feels convenient.

#460, point 3:
- add new ctrl click on item: quick move it to selected tower inventory, and from tower inventory to horadric cube.
- extend shift click on item: now also moves item from item stash to horadric cube.
- all these quick moves now force swap with last item slot of the target container if target container is at full capacity.
- update hints with logic of these controls

My thoughts on use cases:
- convenient tools to avoid item dragging which takes longer - require some time to accustom to.
- from playtesting: after some time I use it almost exclusively instead of dragging; personal use cases: 
- swapping out last item for bonuses that adapt to wave type with single click on prepared item in horadric cube
- swapping out any item - with double click (on tower and cube/stash) - for this dragging could be similarly efficient though 
- bulk inventory swaps / horadric cube swaps

#460, point 4:
- add label showing average level of permanent items in horadric cube below horadric cube; updated `_on_horadric_stash_items_changed()`

My thoughts on use cases:
- Planning cubing recipes
- While playtesting: making sure that average item level is a bit below the level of item I was looking for (assuming the chances are close to optimal that way).

#460, point 5:
- make horadric lock visible in tower
- allow changing state of horadric lock in tower and horadric cube

My thoughts on use cases:
- Clarity and simplicity of item interface: consistent control and display of items, regarding horadric lock
- While playtesting: 
- a "process" of building set of horadric locked items that continues throughout the game. I'd horadric lock most of the items that are equipped by towers. I'd be annoyed if I had to move the item to item stash to do this and re-equip it or otherwise remember to horadric lock it later.  
- in other cases I'd use item grabbing button for recipe and lock useful items in place, without having to move them to item stash. 

#460, point 6:
- add button in upper left corner of item stash with the icon of horadric lock. It is a toggle button that, when on, extends item filter in the item stash by filtering out items that are not horadric locked.

My thoughts on use cases:
- ability to obtain a custom view on the items that for whatever reason player decides to put horadric lock on.
- goes well with mentioned above _a "process" of building set of horadric locked items that continues throughout the game_
- When playtesting: useful for the same reasons as mentioned above, I've used it, but not that often as other improvements. Introduction of sorting button reduced the need for opening custom view too often. I'd still keep this one though.

**Comment by PiotrKaszuba** [comment]
Now, other points about the PR:

- not sure if the code/approach to particular extensions is as good as it could be. I've probably rushed some of these a bit to test them out. However, some of these were quite simple to implement and might even look good implementation wise.
- not sure about the quality of UI introduced elements.
- So, I'd like to ask for both code review and some runtime testing.
- Fortunately, I don't think I've encountered any serious bugs.

**Comment by Kvel2D** [comment]
Almost done with review, didn't find any bugs so far but changed some things.
Need to test in multiplayer.

**Comment by PiotrKaszuba** [comment]
Thank you for this work. I can see the overview of code structure changes. Did anything change functionally?

**Comment by Kvel2D** [comment]
> Thank you for this work. I can see the overview of code structure changes. Did anything change functionally?

No, final behavior is the same.

Except that the "sort item stash" is now done through "Action", which means it gets routed through GameHost and GameClinet, but same behavior basically.

**Review by Kvel2D — APPROVED** [review]
I checked new features in multiplayer and didn't find any issues.

- "Sort item stash" is implemented as Action - no multiplayer desync here
- Filtering out locked items in item stash doesn't affect gameplay - desync not possible
- New item move operations are implemented as existing move/swap Actions - no desyncs here

**Comment by PiotrKaszuba** [comment]
Thank you for accepting the ideas and taking care of this. Even though its already merged - let me know if there's anything else related to this I should look into.

**Pull request merged**
